SELECT ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN (SELECT PARENT_ID, COUNT(ID) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID
HAVING PARENT_ID IS NOT NULL) TEMP
ON ED.ID=TEMP.PARENT_ID
ORDER BY ID