-- 부서별로 부서 ID, 영문 부서명, 평균 연봉을 조회
SELECT HE.DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES HE 
INNER JOIN HR_DEPARTMENT HD
ON HE.DEPT_ID = HD.DEPT_ID
GROUP BY HE.DEPT_ID
ORDER BY AVG_SAL DESC
